# Generated by Django 5.0.8 on 2026-03-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0003_article_highlight_db_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehighlight',
            name='id',
            field=models.BigAutoField(db_comment='하이라이트 PK (문서 필드명 highlight_id). AUTO_INCREMENT', primary_key=True, serialize=False),
        ),
    ]
