# Generated by Django 5.0.8 on 2026-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_event', '0003_add_db_field_comments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='displayevent',
            new_name='event_banne_event_t_f5f5a8_idx',
            old_name='devent_evt_act_ord',
        ),
        migrations.RenameIndex(
            model_name='displayevent',
            new_name='event_banne_start_a_4b5916_idx',
            old_name='devent_start_end',
        ),
        migrations.AlterField(
            model_name='displayevent',
            name='id',
            field=models.BigAutoField(db_comment='이벤트 배너 행 PK (자동 증가)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
