# Generated by Django 5.0.8 on 2026-02-26 06:11

import django.core.validators
import sites.public_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0002_indeuser_socialaccount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='socialaccount',
            name='SocialAccou_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='indeuser',
            new_name='indeUser_email_036a30_idx',
            old_name='indeUser_email_idx',
        ),
        migrations.RenameIndex(
            model_name='indeuser',
            new_name='indeUser_phone_658bc2_idx',
            old_name='indeUser_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='indeuser',
            new_name='indeUser_joined__892f9a_idx',
            old_name='indeUser_joined__idx',
        ),
        migrations.RenameIndex(
            model_name='indeuser',
            new_name='indeUser_profile_6e0476_idx',
            old_name='indeUser_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='indeuser',
            new_name='indeUser_region__bf38c1_idx',
            old_name='indeUser_region__idx',
        ),
        migrations.RenameIndex(
            model_name='indeuser',
            new_name='indeUser_is_acti_ca7a4c_idx',
            old_name='indeUser_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='indeuser',
            new_name='indeUser_created_800efc_idx',
            old_name='indeUser_created_idx',
        ),
        migrations.RenameIndex(
            model_name='publicmembership',
            new_name='publicMembe_email_380364_idx',
            old_name='publicMembe_email_8b7b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='publicmembership',
            new_name='publicMembe_phone_6d843f_idx',
            old_name='publicMembe_phone_2c8e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='publicmembership',
            new_name='publicMembe_joined__e763a1_idx',
            old_name='publicMembe_joined__1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='publicmembership',
            new_name='publicMembe_is_acti_a22f15_idx',
            old_name='publicMembe_is_acti_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='SocialAccou_provide_035b01_idx',
            old_name='SocialAccou_provide_idx',
        ),
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='SocialAccou_email_f_99d462_idx',
            old_name='SocialAccou_email_f_idx',
        ),
        migrations.AlterField(
            model_name='indeuser',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='출생일'),
        ),
        migrations.AlterField(
            model_name='indeuser',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='출생월'),
        ),
        migrations.AlterField(
            model_name='indeuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='출생년도'),
        ),
        migrations.AlterField(
            model_name='indeuser',
            name='id',
            field=models.CharField(default=sites.public_api.models.generate_inde_user_id, editable=False, max_length=15, primary_key=True, serialize=False, verbose_name='회원 ID'),
        ),
        migrations.AlterField(
            model_name='publicmembership',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='출생일'),
        ),
        migrations.AlterField(
            model_name='publicmembership',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='출생월'),
        ),
        migrations.AlterField(
            model_name='publicmembership',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='출생년도'),
        ),
        migrations.AlterField(
            model_name='publicmembership',
            name='member_sid',
            field=models.CharField(default=sites.public_api.models.generate_public_member_sid, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='회원 SID'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user'], name='SocialAccou_user_id_d659b6_idx'),
        ),
    ]
