# Generated by Django 5.0.8 on 2026-03-20 10:19
#
# Fix: RemoveIndex(idx_user) on DB calls MySQL schema_editor which resolves index
# fields against the pre-0010 model; stale state can still reference FK `user`
# (removed in 0010). Physical index on userId already exists — sync state only.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0010_publicuseractivitylog_userid_viewcount_regdate'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='publicuseractivitylog',
                    name='idx_user',
                ),
                migrations.AddIndex(
                    model_name='publicuseractivitylog',
                    index=models.Index(fields=['user_id'], name='idx_user'),
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='publicmembership',
            new_name='publicMembe_sns_pro_67b518_idx',
            old_name='publicMembe_sns_pro_idx',
        ),
        migrations.AddIndex(
            model_name='publicmembership',
            index=models.Index(fields=['status'], name='publicMembe_status_c06b7f_idx'),
        ),
    ]
