# Generated by Django 5.0.8 on 2026-02-26 06:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMemberShip',
            fields=[
                ('memberShipSid', models.CharField(default=api.models.generate_admin_member_sid, editable=False, max_length=15, primary_key=True, serialize=False, verbose_name='회원 SID')),
                ('memberShipId', models.CharField(max_length=50, unique=True, verbose_name='회원 ID')),
                ('memberShipPassword', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('memberShipName', models.CharField(max_length=100, verbose_name='이름')),
                ('memberShipEmail', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('memberShipPhone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('memberShipLevel', models.IntegerField(default=1, verbose_name='회원 레벨')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('login_count', models.IntegerField(default=0, verbose_name='로그인 횟수')),
                ('token_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 토큰 발급 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '관리자 회원',
                'verbose_name_plural': '관리자 회원',
                'db_table': 'adminMemberShip',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['memberShipId'], name='adminMember_memberS_9c4248_idx'), models.Index(fields=['memberShipEmail'], name='adminMember_memberS_63577f_idx'), models.Index(fields=['is_active', 'is_admin'], name='adminMember_is_acti_eb536c_idx')],
            },
        ),
    ]
