# Generated by Django 5.0.8 on 2026-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_doc', '0004_seed_external_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedocinfo',
            name='body_html',
            field=models.TextField(db_comment='HTML 본문(빈 문자열 허용). 회사소개/약관/개인정보는 RichText, 저작권·추천검색어는 Textarea 반영, external_links는 JSON 문자열(인재채용/광고협업 URL) 저장. 이미지는 base64 DB 저장 금지 — 백엔드 PUT에서 S3 URL로 치환 후 저장.'),
        ),
        migrations.AlterField(
            model_name='homepagedocinfo',
            name='doc_type',
            field=models.CharField(db_comment='문서 종류 코드. 허용 7값만: company_intro(회사소개), terms_of_service(이용약관), privacy_policy(개인정보취급방침), article_copyright(아티클 저작권), video_copyright(비디오 저작권), seminar_copyright(세미나 저작권), recommended_search(추천검색어), external_links(외부링크: 인재채용/광고협업 URL). 행당 UNIQUE.', db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='homepagedocinfo',
            name='title',
            field=models.CharField(blank=True, db_comment='www 페이지 제목·메타 등 표시용. NULL 허용. recommended_search는 title=search, external_links는 title=external_links 고정 관례.', max_length=255, null=True),
        ),
    ]
