# Generated by Django 5.0.8 on 2026-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_question', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentquestion',
            index=models.Index(fields=['content_type', 'content_id'], name='idx_cq_content'),
        ),
        migrations.AddIndex(
            model_name='contentquestionanswer',
            index=models.Index(fields=['question_id'], name='idx_cqa_question'),
        ),
        migrations.AddIndex(
            model_name='contentquestionanswer',
            index=models.Index(fields=['content_type', 'content_id'], name='idx_cqa_content'),
        ),
    ]
