# Generated by Django 5.0.8 on 2026-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_messages', '0006_kakaotemplate_emtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaotemplate',
            name='emtitle',
            field=models.CharField(blank=True, default='', help_text='알리고 알림톡 강조표기형 타이틀(emtitle_1)', max_length=500),
        ),
    ]
